// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "aids.proto" (syntax proto3)
// tslint:disable
import { Empty } from './google/protobuf/empty';
import { ServiceType } from '@protobuf-ts/runtime-rpc';
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
/**
 * Mensaje para enviar trozos (chunks) del archivo CSV
 *
 * @generated from protobuf message Chunk
 */
export interface Chunk {
	/**
	 * @generated from protobuf field: bytes content = 1
	 */
	content: Uint8Array;
	/**
	 * @generated from protobuf field: string file_name = 2
	 */
	fileName: string;
}
/**
 * Respuesta después de subir un archivo CSV
 *
 * @generated from protobuf message UploadResponse
 */
export interface UploadResponse {
	/**
	 * @generated from protobuf field: int64 id = 1
	 */
	id: bigint; // ID del dataset guardado en la base de datos
	/**
	 * @generated from protobuf field: string message = 2
	 */
	message: string; // Mensaje de confirmación
}
/**
 * Solicitud para obtener el resumen de un dataset
 *
 * @generated from protobuf message DatasetRequest
 */
export interface DatasetRequest {
	/**
	 * @generated from protobuf field: int64 id = 1
	 */
	id: bigint; // ID del dataset
}
/**
 * Respuesta con el resumen del dataset
 *
 * @generated from protobuf message SummaryResponse
 */
export interface SummaryResponse {
	/**
	 * @generated from protobuf field: string summary_data = 1
	 */
	summaryData: string; // El resumen de pandas.describe() en formato string (ej. JSON)
}
/**
 * Información de un dataset guardado
 *
 * @generated from protobuf message DatasetInfo
 */
export interface DatasetInfo {
	/**
	 * @generated from protobuf field: int64 id = 1
	 */
	id: bigint; // ID del dataset
	/**
	 * @generated from protobuf field: string name = 2
	 */
	name: string; // Nombre original del archivo
	/**
	 * @generated from protobuf field: string created_at = 3
	 */
	createdAt: string; // Fecha de creación (ej. "YYYY-MM-DD HH:MM:SS")
}
/**
 * Respuesta con la lista de datasets guardados
 *
 * @generated from protobuf message DatasetListResponse
 */
export interface DatasetListResponse {
	/**
	 * @generated from protobuf field: repeated DatasetInfo datasets = 1
	 */
	datasets: DatasetInfo[];
}
// @generated message type with reflection information, may provide speed optimized methods
class Chunk$Type extends MessageType<Chunk> {
	constructor() {
		super('Chunk', [
			{ no: 1, name: 'content', kind: 'scalar', T: 12 /*ScalarType.BYTES*/ },
			{ no: 2, name: 'file_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ }
		]);
	}
	create(value?: PartialMessage<Chunk>): Chunk {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.content = new Uint8Array(0);
		message.fileName = '';
		if (value !== undefined) reflectionMergePartial<Chunk>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: Chunk
	): Chunk {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* bytes content */ 1:
					message.content = reader.bytes();
					break;
				case /* string file_name */ 2:
					message.fileName = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === 'throw')
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: Chunk,
		writer: IBinaryWriter,
		options: BinaryWriteOptions
	): IBinaryWriter {
		/* bytes content = 1; */
		if (message.content.length) writer.tag(1, WireType.LengthDelimited).bytes(message.content);
		/* string file_name = 2; */
		if (message.fileName !== '') writer.tag(2, WireType.LengthDelimited).string(message.fileName);
		let u = options.writeUnknownFields;
		if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message Chunk
 */
export const Chunk = new Chunk$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UploadResponse$Type extends MessageType<UploadResponse> {
	constructor() {
		super('UploadResponse', [
			{ no: 1, name: 'id', kind: 'scalar', T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
			{ no: 2, name: 'message', kind: 'scalar', T: 9 /*ScalarType.STRING*/ }
		]);
	}
	create(value?: PartialMessage<UploadResponse>): UploadResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = 0n;
		message.message = '';
		if (value !== undefined) reflectionMergePartial<UploadResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: UploadResponse
	): UploadResponse {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* int64 id */ 1:
					message.id = reader.int64().toBigInt();
					break;
				case /* string message */ 2:
					message.message = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === 'throw')
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: UploadResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions
	): IBinaryWriter {
		/* int64 id = 1; */
		if (message.id !== 0n) writer.tag(1, WireType.Varint).int64(message.id);
		/* string message = 2; */
		if (message.message !== '') writer.tag(2, WireType.LengthDelimited).string(message.message);
		let u = options.writeUnknownFields;
		if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message UploadResponse
 */
export const UploadResponse = new UploadResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DatasetRequest$Type extends MessageType<DatasetRequest> {
	constructor() {
		super('DatasetRequest', [
			{ no: 1, name: 'id', kind: 'scalar', T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
		]);
	}
	create(value?: PartialMessage<DatasetRequest>): DatasetRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = 0n;
		if (value !== undefined) reflectionMergePartial<DatasetRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: DatasetRequest
	): DatasetRequest {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* int64 id */ 1:
					message.id = reader.int64().toBigInt();
					break;
				default:
					let u = options.readUnknownField;
					if (u === 'throw')
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: DatasetRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions
	): IBinaryWriter {
		/* int64 id = 1; */
		if (message.id !== 0n) writer.tag(1, WireType.Varint).int64(message.id);
		let u = options.writeUnknownFields;
		if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message DatasetRequest
 */
export const DatasetRequest = new DatasetRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SummaryResponse$Type extends MessageType<SummaryResponse> {
	constructor() {
		super('SummaryResponse', [
			{ no: 1, name: 'summary_data', kind: 'scalar', T: 9 /*ScalarType.STRING*/ }
		]);
	}
	create(value?: PartialMessage<SummaryResponse>): SummaryResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.summaryData = '';
		if (value !== undefined) reflectionMergePartial<SummaryResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: SummaryResponse
	): SummaryResponse {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string summary_data */ 1:
					message.summaryData = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === 'throw')
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: SummaryResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions
	): IBinaryWriter {
		/* string summary_data = 1; */
		if (message.summaryData !== '')
			writer.tag(1, WireType.LengthDelimited).string(message.summaryData);
		let u = options.writeUnknownFields;
		if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message SummaryResponse
 */
export const SummaryResponse = new SummaryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DatasetInfo$Type extends MessageType<DatasetInfo> {
	constructor() {
		super('DatasetInfo', [
			{ no: 1, name: 'id', kind: 'scalar', T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
			{ no: 2, name: 'name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
			{ no: 3, name: 'created_at', kind: 'scalar', T: 9 /*ScalarType.STRING*/ }
		]);
	}
	create(value?: PartialMessage<DatasetInfo>): DatasetInfo {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = 0n;
		message.name = '';
		message.createdAt = '';
		if (value !== undefined) reflectionMergePartial<DatasetInfo>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: DatasetInfo
	): DatasetInfo {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* int64 id */ 1:
					message.id = reader.int64().toBigInt();
					break;
				case /* string name */ 2:
					message.name = reader.string();
					break;
				case /* string created_at */ 3:
					message.createdAt = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === 'throw')
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: DatasetInfo,
		writer: IBinaryWriter,
		options: BinaryWriteOptions
	): IBinaryWriter {
		/* int64 id = 1; */
		if (message.id !== 0n) writer.tag(1, WireType.Varint).int64(message.id);
		/* string name = 2; */
		if (message.name !== '') writer.tag(2, WireType.LengthDelimited).string(message.name);
		/* string created_at = 3; */
		if (message.createdAt !== '') writer.tag(3, WireType.LengthDelimited).string(message.createdAt);
		let u = options.writeUnknownFields;
		if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message DatasetInfo
 */
export const DatasetInfo = new DatasetInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DatasetListResponse$Type extends MessageType<DatasetListResponse> {
	constructor() {
		super('DatasetListResponse', [
			{
				no: 1,
				name: 'datasets',
				kind: 'message',
				repeat: 2 /*RepeatType.UNPACKED*/,
				T: () => DatasetInfo
			}
		]);
	}
	create(value?: PartialMessage<DatasetListResponse>): DatasetListResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.datasets = [];
		if (value !== undefined) reflectionMergePartial<DatasetListResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: DatasetListResponse
	): DatasetListResponse {
		let message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* repeated DatasetInfo datasets */ 1:
					message.datasets.push(DatasetInfo.internalBinaryRead(reader, reader.uint32(), options));
					break;
				default:
					let u = options.readUnknownField;
					if (u === 'throw')
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
						);
					let d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d
						);
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: DatasetListResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions
	): IBinaryWriter {
		/* repeated DatasetInfo datasets = 1; */
		for (let i = 0; i < message.datasets.length; i++)
			DatasetInfo.internalBinaryWrite(
				message.datasets[i],
				writer.tag(1, WireType.LengthDelimited).fork(),
				options
			).join();
		let u = options.writeUnknownFields;
		if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message DatasetListResponse
 */
export const DatasetListResponse = new DatasetListResponse$Type();
/**
 * @generated ServiceType for protobuf service AidsService
 */
export const AidsService = new ServiceType('AidsService', [
	{ name: 'UploadCsv', options: {}, I: Chunk, O: UploadResponse },
	{ name: 'GetDatasetSummary', options: {}, I: DatasetRequest, O: SummaryResponse },
	{ name: 'ListSavedDatasets', options: {}, I: Empty, O: DatasetListResponse }
]);
