// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "aids.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AidsService } from "./aids";
import type { ChartResponse } from "./aids";
import type { ChartRequest } from "./aids";
import type { DatasetListResponse } from "./aids";
import type { Empty } from "./google/protobuf/empty";
import type { SummaryResponse } from "./aids";
import type { DatasetRequest } from "./aids";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { UploadResponse } from "./aids";
import type { Chunk } from "./aids";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Servicio gRPC para el análisis de datos
 *
 * @generated from protobuf service AidsService
 */
export interface IAidsServiceClient {
    /**
     * Sube un archivo CSV en streaming
     *
     * @generated from protobuf rpc: UploadCsv
     */
    uploadCsv(input: Chunk, options?: RpcOptions): UnaryCall<Chunk, UploadResponse>;
    /**
     * Obtiene el resumen de un dataset por su ID
     *
     * @generated from protobuf rpc: GetDatasetSummary
     */
    getDatasetSummary(input: DatasetRequest, options?: RpcOptions): UnaryCall<DatasetRequest, SummaryResponse>;
    /**
     * Obtiene la lista de todos los datasets guardados
     *
     * @generated from protobuf rpc: ListSavedDatasets
     */
    listSavedDatasets(input: Empty, options?: RpcOptions): UnaryCall<Empty, DatasetListResponse>;
    /**
     * Borra un dataset
     *
     * @generated from protobuf rpc: DeleteDataset
     */
    deleteDataset(input: DatasetRequest, options?: RpcOptions): UnaryCall<DatasetRequest, Empty>;
    /**
     * Para descargar un dataset
     *
     * @generated from protobuf rpc: DownloadDataset
     */
    downloadDataset(input: DatasetRequest, options?: RpcOptions): UnaryCall<DatasetRequest, Chunk>;
    /**
     * For getting a chart with specific fields
     *
     * @generated from protobuf rpc: GetChart
     */
    getChart(input: ChartRequest, options?: RpcOptions): UnaryCall<ChartRequest, ChartResponse>;
}
/**
 * Servicio gRPC para el análisis de datos
 *
 * @generated from protobuf service AidsService
 */
export class AidsServiceClient implements IAidsServiceClient, ServiceInfo {
    typeName = AidsService.typeName;
    methods = AidsService.methods;
    options = AidsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Sube un archivo CSV en streaming
     *
     * @generated from protobuf rpc: UploadCsv
     */
    uploadCsv(input: Chunk, options?: RpcOptions): UnaryCall<Chunk, UploadResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Chunk, UploadResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Obtiene el resumen de un dataset por su ID
     *
     * @generated from protobuf rpc: GetDatasetSummary
     */
    getDatasetSummary(input: DatasetRequest, options?: RpcOptions): UnaryCall<DatasetRequest, SummaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DatasetRequest, SummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Obtiene la lista de todos los datasets guardados
     *
     * @generated from protobuf rpc: ListSavedDatasets
     */
    listSavedDatasets(input: Empty, options?: RpcOptions): UnaryCall<Empty, DatasetListResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, DatasetListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Borra un dataset
     *
     * @generated from protobuf rpc: DeleteDataset
     */
    deleteDataset(input: DatasetRequest, options?: RpcOptions): UnaryCall<DatasetRequest, Empty> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DatasetRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Para descargar un dataset
     *
     * @generated from protobuf rpc: DownloadDataset
     */
    downloadDataset(input: DatasetRequest, options?: RpcOptions): UnaryCall<DatasetRequest, Chunk> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DatasetRequest, Chunk>("unary", this._transport, method, opt, input);
    }
    /**
     * For getting a chart with specific fields
     *
     * @generated from protobuf rpc: GetChart
     */
    getChart(input: ChartRequest, options?: RpcOptions): UnaryCall<ChartRequest, ChartResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChartRequest, ChartResponse>("unary", this._transport, method, opt, input);
    }
}
