# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aids_pb2 as aids__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aids_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AidsServiceStub(object):
    """Servicio gRPC para el análisis de datos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCsv = channel.unary_unary(
                '/AidsService/UploadCsv',
                request_serializer=aids__pb2.Chunk.SerializeToString,
                response_deserializer=aids__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.GetDatasetSummary = channel.unary_unary(
                '/AidsService/GetDatasetSummary',
                request_serializer=aids__pb2.DatasetRequest.SerializeToString,
                response_deserializer=aids__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.ListSavedDatasets = channel.unary_unary(
                '/AidsService/ListSavedDatasets',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=aids__pb2.DatasetListResponse.FromString,
                _registered_method=True)
        self.DeleteDataset = channel.unary_unary(
                '/AidsService/DeleteDataset',
                request_serializer=aids__pb2.DatasetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DownloadDataset = channel.unary_unary(
                '/AidsService/DownloadDataset',
                request_serializer=aids__pb2.DatasetRequest.SerializeToString,
                response_deserializer=aids__pb2.Chunk.FromString,
                _registered_method=True)
        self.GetChart = channel.unary_unary(
                '/AidsService/GetChart',
                request_serializer=aids__pb2.ChartRequest.SerializeToString,
                response_deserializer=aids__pb2.ChartResponse.FromString,
                _registered_method=True)


class AidsServiceServicer(object):
    """Servicio gRPC para el análisis de datos
    """

    def UploadCsv(self, request, context):
        """Sube un archivo CSV en streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetSummary(self, request, context):
        """Obtiene el resumen de un dataset por su ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSavedDatasets(self, request, context):
        """Obtiene la lista de todos los datasets guardados
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataset(self, request, context):
        """Borra un dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadDataset(self, request, context):
        """Para descargar un dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChart(self, request, context):
        """For getting a chart with specific fields
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AidsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCsv': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCsv,
                    request_deserializer=aids__pb2.Chunk.FromString,
                    response_serializer=aids__pb2.UploadResponse.SerializeToString,
            ),
            'GetDatasetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetSummary,
                    request_deserializer=aids__pb2.DatasetRequest.FromString,
                    response_serializer=aids__pb2.SummaryResponse.SerializeToString,
            ),
            'ListSavedDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSavedDatasets,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=aids__pb2.DatasetListResponse.SerializeToString,
            ),
            'DeleteDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataset,
                    request_deserializer=aids__pb2.DatasetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DownloadDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadDataset,
                    request_deserializer=aids__pb2.DatasetRequest.FromString,
                    response_serializer=aids__pb2.Chunk.SerializeToString,
            ),
            'GetChart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChart,
                    request_deserializer=aids__pb2.ChartRequest.FromString,
                    response_serializer=aids__pb2.ChartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AidsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AidsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AidsService(object):
    """Servicio gRPC para el análisis de datos
    """

    @staticmethod
    def UploadCsv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AidsService/UploadCsv',
            aids__pb2.Chunk.SerializeToString,
            aids__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AidsService/GetDatasetSummary',
            aids__pb2.DatasetRequest.SerializeToString,
            aids__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSavedDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AidsService/ListSavedDatasets',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            aids__pb2.DatasetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AidsService/DeleteDataset',
            aids__pb2.DatasetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AidsService/DownloadDataset',
            aids__pb2.DatasetRequest.SerializeToString,
            aids__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AidsService/GetChart',
            aids__pb2.ChartRequest.SerializeToString,
            aids__pb2.ChartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
